#include "game.h"

/* The house. Rows are up to 16 wide; anything missing is wall.
 *   # wall   . floor   : grate (ghost or cat)   f cat flap (cat only)
 *   D locked door (a servant with the key)   C cracked wall (armor smashes it)
 *   _ pressure plate (held by any host or crate)   G gate (open while every plate is held)
 *   X exit mirror (ghost only)   @ you   c cat   a armor   s servant   k key   b crate
 * Priests patrol a straight line between two points, every `stride` ticks. */
LevelDef kLevels[] = {
    {"The Cat Flap",
     {"################",
      "#......#.......#",
      "#......#.......#",
      "#.@.c..f......X#",
      "#......#.......#",
      "################"},
     0, {{0}}, "A ghost cannot fit through a cat flap. A cat can.", 13},

    {"The Bell",
     {"################",
      "#@.............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#.............X#",
      "################"},
     1, {{7, 1, 7, 4, 2}}, "The priest sees straight ahead. Wait for him to look away.", 17},

    {"Locked Door",
     {"################",
      "#......#.......#",
      "#.@.s..#.......#",
      "#....k.D......X#",
      "#......#.......#",
      "################"},
     0, {{0}}, "A servant can carry a key. A ghost cannot.", 14},

    {"Heavy Lifting",
     {"################",
      "#......#.......#",
      "#.@.a..C......X#",
      "#......#.......#",
      "################"},
     0, {{0}}, "Armor is slow, and strong enough to break a cracked wall.", 17},

    {"Weight on the Plate",
     {"################",
      "#.......#......#",
      "#.@.c...G.....X#",
      "#.......#......#",
      "####:###########",
      "#..._..#########",
      "################"},
     0, {{0}}, "Something has to stand on the plate to keep the gate open.", 19},

    {"Night Watch",
     {"################",
      "#@.............#",
      "#..............#",
      "#..............#",
      "#..............#",
      "#.............X#",
      "################"},
     2, {{2, 3, 13, 3, 2}, {8, 1, 8, 5, 2}}, "Two priests, two ways of looking.", 17},

    {"Housekeeping",
     {"################",
      "#......#.......#",
      "#.@.s..#.......#",
      "#....k.D......X#",
      "#......#.......#",
      "################"},
     1, {{3, 1, 3, 4, 2}}, "Get the key without getting caught.", 16},

    {"The Grand Hall",
     {"################",
      "#.......#..#...#",
      "#.@.....G..C..X#",
      "#..c....#..#...#",
      "#....a..#......#",
      "####:###########",
      "#..._..#########",
      "################"},
     1, {{6, 1, 6, 4, 2}}, "Something to hold the gate, something to break the wall.", 25},

    {"Two Doors",
     {"################",
      "#......#...#...#",
      "#.@.s.kD...D..X#",
      "#......#.k.#...#",
      "################"},
     0, {{0}}, "One key, one door. Then another.", 15},

    {"The Pantry",
     {"################",
      "#......#.......#",
      "#.@..s.D.k.....#",
      "#..k...#.......#",
      "#......#####D###",
      "#......#......X#",
      "################"},
     1, {{11, 1, 11, 3, 2}}, "The key to the second door is behind the first.", 23},

    {"Weight of Two",
     {"################",
      "#.......#......#",
      "#.@.a.b.G.....X#",
      "#..c.._.#......#",
      "####:###########",
      "#..._..#########",
      "################"},
     0, {{0}}, "The gate wants both plates held at once.", 24},

    {"Crossing Guard",
     {"################",
      "#.....#........#",
      "#.@.c.f........#",
      "#.....#...#....#",
      "#.....#...#.X..#",
      "################"},
     1, {{8, 1, 8, 4, 2}}, "A ghost cannot use a cat flap. He watches the far side.", 13},

    {"Patient Hands",
     {"################",
      "#..............#",
      "#@.s.k..D.....X#",
      "#..............#",
      "#..............#",
      "################"},
     2, {{5, 1, 5, 4, 2}, {11, 4, 11, 1, 2}}, "Fetch the key while both of them are looking elsewhere.", 15},

    {"Stone and Bone",
     {"################",
      "#.......#......#",
      "#.@.a.b.C.....X#",
      "#.......#......#",
      "#..c....#......#",
      "####:###########",
      "#..._.G.........",
      "################"},
     0, {{0}}, "Some walls fall, some gates rise.", 22},

    {"Three Rooms",
     {"################",
      "#....#....#..#.#",
      "#.@c.f.sk.Da.CX#",
      "#....#....#..#.#",
      "################"},
     1, {{9, 1, 9, 3, 2}}, "Cat, servant, armor: in that order.", 25},

    {"Grate Run",
     {"################",
      "#@.....#.......#",
      "#......:.......#",
      "#......#.......#",
      "####:###.#######",
      "#......#.#.#.#X#",
      "#......:.......#",
      "################"},
     1, {{8, 6, 14, 6, 2}}, "Grates are for ghosts and cats. Hide in the alcoves; he only sees along his line.", 29},

    {"Sentry Flap",
     {"################",
      "#......#.......#",
      "#.@.c..f...X...#",
      "#......#.......#",
      "#......#.......#",
      "################"},
     1, {{9, 1, 9, 4, 2}}, "Cats are safe from the bell, but the flap opens onto his beat.", 10},

    {"Two Keys",
     {"################",
      "#......#.......#",
      "#.@.s.k#.......#",
      "#......D...k...#",
      "#......#.......#",
      "#####D##########",
      "#.............X#",
      "################"},
     0, {{0}}, "The second key is the far side of the first door.", 19},

    {"Push and Hold",
     {"################",
      "#.......#......#",
      "#.@.a.b.#......#",
      "#....._.G.....X#",
      "#.......#......#",
      "################"},
     1, {{2, 4, 7, 4, 2}}, "Crates can hold a plate as well as a host can.", 17},

    {"Three Bells",
     {"################",
      "#@.............#",
      "######.#####.###",
      "#..............#",
      "###.#####.######",
      "#.............X#",
      "################"},
     3, {{1, 3, 14, 3, 2}, {1, 5, 12, 5, 3}, {8, 1, 14, 1, 4}}, "Three bells, three rhythms. Count.", 41},

    {"The Vault",
     {"################",
      "#.......#.....##",
      "#.@.a...C.bs.Gk#",
      "#.......#.._..##",
      "#.......#####D##",
      "#........#.....#",
      "#........#...X.#",
      "################"},
     1, {{1, 5, 7, 5, 2}}, "Break in, put the crate on the plate, take the key, open the door.", 33},

    {"Watched Hall",
     {"################",
      "#......#.......#",
      "#.@.c..f...s.k.#",
      "#......#.......#",
      "#......#####D###",
      "#......#......X#",
      "################"},
     1, {{10, 1, 10, 3, 2}}, "Cat through the flap, servant for the key, all under his eye.", 20},

    {"Grand Tour",
     {"################",
      "#....#....#....#",
      "#.@a.C.sk.D.c.fX",
      "#....#....#....#",
      "################"},
     1, {{7, 1, 7, 3, 2}}, "Armor, servant, cat, and a ghost in the wrong place.", 21},
};
const int kLevelCount = (int)(sizeof(kLevels) / sizeof(kLevels[0]));
